<template>
  <section>
    <div class="home-title">
      <h1>The Community Showcase</h1>
      <p>
        Browse through a collection of imaginative and visually stunning images generated by DALL-E AI.
      </p>
    </div>
    <div class="search-input">
      <div class="input-wrapper">
        <div class="label-container">
          <label for="text">Search Posts</label>
        </div>
        <input type="text" id="text" name="text" placeholder="Search Someting..." v-model="searchText" required>
      </div>
    </div>
    <div class="mt-10">
    <div class="flex justify-center items-center" v-if="loading">
      <h3>Loading...</h3>
    </div>
    <div v-else>
        <h2 class="search-text" v-if="searchText">
          Showing result for <span>{{ searchText }}</span>
        </h2>
        <div class="cards-wrapper">
          <template v-if="filteredPost?.length > 0">
            <Card v-for="(post, i) in filteredPost" :post="post" :key="i" />
          </template>
          <h2 v-else class="title">{{ title }}</h2>
        </div>
    </div>
    </div>
  </section>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import Card from '../components/Card.vue';

const searchText = ref('');
const loading = ref(false);
const allPost = ref([]);
const title = ref('');

const fetchPost = async () => {
  try{
      loading.value = true;
      const resposne = await fetch('http://localhost:8000/api/v1/post', {
        method: 'GET',
        headers: {
          "Content-Type": 'application/json'
        }
      });

     const result = await resposne.json();
      allPost.value = result.data.reverse();
      console.log('result ', result);
      if(result.data.length === 0){
        title.value = "NO post yet";
      }
    } catch(err){
      console.log('prompt generating error ', err);
    } finally{
      loading.value = false;
    }
}

const filteredPost = computed(() => {
  if(searchText.value === ''){
    return allPost.value;
  } else {
    const result = allPost.value.filter(item => item.name.toLowerCase().includes(searchText.value.toLowerCase()) ||
     item.prompt.toLowerCase().includes(searchText.value.toLowerCase()));
     if(result.length === 0){
      title.value = "No search found";
     }
     return result;
  }
});

onMounted( async () => {
  await fetchPost()
})
</script>
